name: Nightly CI

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - 'v*'
  workflow_dispatch:

jobs:
  build-tauri:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: checkout release
        uses: actions/checkout@v4
        with:
          ref: "gh-pages"
          path: "last"

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: get yarn cache directory path
        id: yarn-cache-dir-path
        shell: bash
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: setup yarn cache
        uses: actions/cache/restore@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: setup yarn dependencies
        run: yarn

      - name: build
        run: yarn build
        env:
          ref: ${{ github.sha }}

      - name: pack
        run: |
          rm -rf dist/nightly
          rm -rf last/nightly
          mv dist last/nightly
          touch last/.nojekyll

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: last
          clean: true
